### ISSUE TITLE
멀티버스2 관련 질문

### ISSUE THREAD

**Issue by gnsdyd12** [SSAFY-09-D7/term1-group1#13]
https://www.acmicpc.net/problem/18869

2차원 객체 배열을 생성해서 풀었는데 2차원 배열을 각 행마다 오름차순 정렬하고 싶으면 어떻게 해줘야 하나요?  
ex) Pair[][] arr = new Pair[N][M]; 에서 arr[i]행 오름차순 정렬 
comparator로 해봐도 잘 안되네요.

그래서 결국 2차원 ArrayList로 바꿔서 Collections.sort로 정렬해줬는데 이건 되는데 배열도 되는지 궁금합니다 ㅠ

**Comment by a91516151** [comment]
Arrays.sort(arr[i], comparator 구현체) 또는 Pair 클래스에서 Comparable을 implements 해보셨는데 안되는 건가요?
