### ISSUE TITLE
[SWEA 5432] 쇠막대기 자르기 런타임 에러

### ISSUE THREAD

**Issue by gnsdyd12** [SSAFY-09-D7/term1-group1#8]
stack 메모리 문제인가 싶어서 전역으로도 선언해봤는데 계속 런타임 에러 뜨네요
이유가 뭘까요

**Comment by Dayoung1014** [comment]
혹시 stack.isEmpty()일 때 pop 하신거는 아닐까요? 아직 해결 전이시라면 코드 함께 남겨주시면 같이 찾아보겠습니다!

**Comment by gnsdyd12** [comment]
stack 비어있을때 pop해서 그런거 맞네요 처리를 안해줬었네요 ㅠ 감사합니다
